---
# 
name: Publish npm package
on:
  push:
    tags:
      - '*'
env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
jobs:
  build-and-publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: |
          npm ci
          npm run build --if-present
          npm run test:coverage --if-present
          npm publish
        